version: '3.4'

services:
  northstar.api:
    image: ${DOCKER_REGISTRY-}northstarapi
    container_name: Northstar.api
    build:
      context: .
      dockerfile: src/NorthStar.Api/Dockerfile
    depends_on:
      - northstar-db

  northstar-db:
    image: postgres:latest
    container_name: Northstar.Db
    environment:
      - POSTGRES_DB=northstar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
     - 5432:5432

  northstar-seq:
    image: datalust/seq:latest
    container_name: Northstar.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  northstar-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: Northstar.Identity
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      [ "start-dev",  "--import-realm" ]
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/northstar-realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - 18080:8080